import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./providers";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Discuss",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Provider>
          <div className="fixed container top-10 left-1/2 -translate-x-1/2">
            <Header />
          </div>
          <div className="container mx-auto px-10 my-32">
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
